### ISSUE TITLE
关于数组的语法，我觉得这样更好一些

### ISSUE THREAD

**Issue by tomener** [crossoverJie/gscript#12]
// Declare and initialize
int[] a = [1,2,3]
println(a)

// Declare an empty array and specify the length
int[] b = (4)[];
println(b)

// Append data to array.
a.append(4)
println(a);

**Comment by crossoverJie** [comment]
感谢建议。
1. 数组定义是用 `[]` 还是 `{}`，当前我是参考的 Go 使用 `{}`，因为编译器本身是 Go 开发的，所以我个人写起来不会记混，这个只是个人喜好罢了。
2. append 函数这个其实也是参考的 Go 的语义，不过这也是 Go 被喷的点之一；这个建议不错，后面我调整下。

**Comment by tomener** [comment]
因为现在大部分语言都是用的**[]**，其它语言转变过来比较易理解，直观，不会有抵触心理。

**Comment by crossoverJie** [comment]
`append()` 函数已优化，不过数组语法还得考虑一下。
https://github.com/crossoverJie/gscript/pull/15
