### ISSUE TITLE
提供的二进制文件里面没有windows版本

### ISSUE THREAD

**Issue by fenginsc** [crossoverJie/gscript#18]
提供的二进制文件里面没有windows版本

**Comment by crossoverJie** [comment]
暂时没有 window 设备进行编译，可以参考这里手动安装。
https://github.com/crossoverJie/gscript/issues/14

也可以在线试用：
https://gscript.crossoverjie.top/

**Comment by crossoverJie** [comment]
现已提供 docker 版本：
https://github.com/crossoverJie/gscript#docker
