### ISSUE TITLE
增加语义分析/类型检查

### ISSUE THREAD

**Issue by kkkunny** [crossoverJie/gscript#23]
gscript在定位上是一门强类型的语言，然而以下代码却能正常编译并运行
```c
int getNumber(){
  return true;  // 返回值应该是一个整型而不是布尔
}
println(getNumber());
```
这显然是与gscript强类型的定位相悖的
所以是否有必要在语法解析和解释之间增加一个类型检查（语义分析）的步骤？

**Comment by crossoverJie** [comment]
感谢反馈，这块已经列入了 TODO，只是还没时间做，比如现在声明了返回值其实不返回也会执行。

**Comment by crossoverJie** [comment]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/15684156/199051932-9bba350a-3a70-4220-8f28-774f1a1904c7.png">

现已修复。
