### ISSUE TITLE
可惜已停更

### ISSUE THREAD

**Issue by snail2sky** [crossoverJie/gscript#30]

**Comment by crossoverJie** [comment]
由于精力有限，暂时没有加新功能了，有什么想法可以提 issue，我有时间的话可以处理。

**Comment by snail2sky** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crossoverJie/gscript"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月29日(星期三) 中午1:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [crossoverJie/gscript] 可惜已停更 (Issue #30)





 
由于精力有限，暂时没有加新功能了，有什么想法可以提 issue，我有时间的话可以处理。

**Comment by snail2sky** [comment]
关闭issue
